name: 'CompatHelper detector'
description: 'Detect if PR is a CompatHelper or dependabot PR'
author: 'Angus Moore'

branding:
  icon: 'aperture'
  color: 'gray-dark'

outputs:
  is_dependabot:
    description: 'Boolean for if this is a dependabot/CompatHelper branch'
    value: ${{ steps.dependabot.outputs.is_dependabot }}

runs:
  using: 'composite'
  steps:
    - name: Detect if dependabot PR
      id: dependabot 
      run: |
        echo "is_dependabot=$(julia --project -e 'include(joinpath(ENV["GITHUB_ACTION_PATH"], "autodetect-dependabot.jl")); print(AutodetectDependabot.is_dependabot_job())')" >> $GITHUB_OUTPUT
      shell: bash

